// export interface ICart {
//   // "status": 201,
//   // "success": true,
//   "message": "Product added to cart successfully",
//   "data": {
//     // "cartItemId": 3,
//     "quantity": 2,
//     "createdAt": "2023-03-20T01:14:39.6942417",
//     "movieId": 5,
//     "movie": {
//       "id": 5,
//       "name": "ffff",
//       "description": "hhhh",
//       "price": 30,
//       "imageURL": "kkkk",
//       "startDate": "2024-06-06T00:00:00",
//       "endDate": "2025-06-05T00:00:00",
//       "movieCategory": 1,
//       "actors_Movies": null,
//       "cinemaId": 1,
//       "cinema": null,
//       "producerId": 1,
//       "producer": null
//     },
//     "userId": "1bf04ce8-8678-49ce-b930-531d2bd65a8a",
//     "user": {
//       "firstName": "bassant",
//       "lastName": "adel",
//       "id": "1bf04ce8-8678-49ce-b930-531d2bd65a8a",
//       "userName": "Bassant",
//       "normalizedUserName": "BASSANT",
//       "email": "bassant@gmail.com",
//       "normalizedEmail": "BASSANT@GMAIL.COM",
//       "emailConfirmed": false,
//       "passwordHash": "AQAAAAEAACcQAAAAEIQlN4F+vq/2/AZ6O28U4hE5HYyrnqQdPb7G43hzFnZeyC4kCh4ENjwQiIAiXY2n3w==",
//       "securityStamp": "CXY226VWSP472DPUXK55F6JHCDOSIFUR",
//       "concurrencyStamp": "0111194b-33a5-474b-b8a2-ad3c29bcfe21",
//       "phoneNumber": null,
//       "phoneNumberConfirmed": false,
//       "twoFactorEnabled": false,
//       "lockoutEnd": null,
//       "lockoutEnabled": true,
//       "accessFailedCount": 0
//     }
